config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end


  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]


  # Sessions
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'



  root to: 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  # has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  # has_many :followed_users, through: :relationships, source: :followed
  #
  # has_many :reverse_relationships, foreign_key: "followed_id",
  #                                  class_name:  "Relationship",
  #                                  dependent:   :destroy
  #
  # has_many :followers, through: :reverse_relationships, source: :follower

  has_attached_file :avatar, :styles => { :medium => "500x500>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :username, :first_name, :last_name, presence: true
  validates :username, uniqueness: true

  validates :password, presence: true
  validates :password_confirmation, presence: true

  # def following?(other_user)
  #   relationships.find_by_followed_id(other_user.id)
  # end
  #
  # def follow!(other_user)
  #   relationships.create!(followed_id: other_user.id)
  # end
  #
  # def unfollow!(other_user)
  #   relationships.find_by_followed_id(other_user.id).destroy
  # end
  #
  # def feed
  #   post.from_users_followed_by(self)
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])  
  end


  def edit
    if session[:current_user] == params[:id].to_i
      @user = User.find(params[:id])
    else
      redirect_to users_path
    end
  end

  def update
    if session[:current_user] == params[:id].to_i
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to users_path
      else
        render :edit
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:current_user] = nil
    redirect_to users_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  private
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :password,
    :password_confirmation, :discipline, :artist_statement, :location, :contact_info,
    :instagram, :facebook, :twitter, :website, :avatar)
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<div>
<%= form_for(@user) do |f| %>
  <h3>Required Information</h3>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <hr class="hr_style">
  <h3>Optional Information</h3>
  <p>
    <%= f.label :discipline %>
    <%= f.text_field :discipline %>

    <%= f.label :artist_statement %>
    <%= f.text_field :artist_statement %>

    <%= f.label :website %>
    <%= f.text_field :website %>
  </p>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :contact_info %>
    <%= f.text_field :contact_info %>
  </p>
  <p>
    <%= f.label :instagram %>
    <%= f.text_field :instagram %>

    <%= f.label :facebook %>
    <%= f.text_field :facebook %>

    <%= f.label :twitter %>
    <%= f.text_field :twitter %>
  </p>
  <p>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </p>
  <hr class="hr_style">
  <p class="button">
    <%= f.submit %>
  <p>
<% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_users.html.erb
<% if user.avatar.present? %>
<%= image_tag user.avatar.url(:thumb) %>
<% end %>
<div id="users_page">
<div class="user_index"><p>Username: <%= link_to(user.username, user_path(user)) %></p></div>
<div class="user_index"><p>Name: <%= user.first_name %> <%= user.last_name %></p></div>
<!-- <div class="user_index"><p>Location: <%= user.location %></p></div> -->
<p>ID: <%= user.id %></p>
<!-- <p>Discipline: <%= user.discipline %></p>
<p>Description: <%= user.artist_statement %></p>
<p>Contact: <%= user.contact_info%></p>
<p>Instagram: <%= user.instagram %></p>
<p>Facebook: <%= user.facebook %></p>
<p>Twitter: <%= user.twitter %></p>
<p>Website: <%= user.website %></p> -->
<% if session[:current_user] == user.id %><br>

  <div id="user_navigation">
    <%= link_to('Edit Profile', edit_user_path(user)) %>
  </div>

  <div id="user_navigation">
    <%= link_to('Delete Account', user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete your account?" }) %>
  </div>

<% end %>
<hr class="hr_style">
</div>

app/views/users/edit.html.erb
<div class="about_content"><h2>Edit Profile</h2></div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="about_content"><h2>Contributors</h2></div>

<% @users.each do |current_user| %>
<%= render partial: 'users', locals: {user: current_user} %>
<% end %>

app/views/users/new.html.erb
<div class="about_content"><h2>New User Registration</h2></div>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="show_user_content">
<%= image_tag @user.avatar.url(:thumb) %>
<span class="title">Posts by: <%= @user.first_name %> <%= @user.last_name %> <span class="separator">//</span> <span class="username_feed"><%= link_to( @user.username, user_path( @user )) %></span></span>
<p><%= @user.artist_statement %> <%= @user.location %> <%= @user.website %></p>
</div>
<div class="about_content">

<% @user.posts.each do |post| %>
  <div class="post_content">
    <span class="title"><%= link_to(post.title, post_path(post))%></span>
    <span class="separator">//</span>  <span class="post_date"><%= post.date %></span>
  </div>
    <% if post.attachment.present? %>

    <div class="containingBlock">

      <div class="embed_frame"><%= image_tag post.attachment.url(:medium) %></div>

    </div>
    <% end %>
      <%= render partial: 'posts/embed', locals: { post: post } %>
      <p><%= post.article %></p>

<hr class="hr_style">


<% end %>
  </div>