config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end


  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]


  # Sessions
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'



  root to: 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_attached_file :attachment, :styles => { :medium => "800x800>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :attachment, :less_than => 5.megabytes
  validates :title, :date, presence: true

  def strip_link
    link = self.embed_link
    if link.include? 'youtube'
      self.embed_link = link.scan(/=\p{Alnum}*/).first.gsub(/[=]/, '')
    elsif link.include? 'vimeo'
      self.embed_link = link.scan(/m\/\p{N}*/).first.gsub(/[m\/\/]/, '')
    elsif link.include? 'tracks'
     self.embed_link = link.scan(/tracks\/\d{1,}/).first
    elsif link.include? 'playlists'
     self.embed_link = link.scan(/playlists\/\d{1,}/).first
    end
    return link
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:current_user]
    @post.strip_link
    if @post.save
      redirect_to(posts_path)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  # def search
  #   @post = Post.where(':')
  # end

  def edit
    @post = Post.find(params[:id])
    redirect_to posts_path unless session[:current_user] == @post.user_id
  end

  def update
    @post = Post.find(params[:id])
    if @post.user_id == session[:current_user] #if you authored the post
        @post.update(post_params) # save with post paramaters
        @post.strip_link # calls strip_link method on @post instance variable
        @post.save
        redirect_to(post_path(@post))
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to(posts_path)
  end

  private
  def post_params
    params.require(:post).permit(:title, :article, :date, :category, :attachment, :embed_link)
  end

end

app/views/posts/_embed.html.erb
<div class="containingBlock">
<% if post.embed_link.present? %>


  <% if post.embed_link && post.embed_link.length == 11 %>

    <div class="embed_frame"><iframe width="100%" height="450" src="//www.youtube.com/embed/<%= post.embed_link %>"frameborder="0" allowfullscreen></iframe></div>

  <% elsif post.embed_link && post.embed_link.include?("tracks") %>

    <div class="embed_frame"><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/<%= post.embed_link %>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=false&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe></div>

  <% elsif post.embed_link && post.embed_link.include?("playlists") %>

  <div class="embed_frame"><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/<%= post.embed_link %>&amp;auto_play=false&amp;hide_related=false&amp;show_comments=false&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe></div>

  <% elsif post.embed_link && post.embed_link.include?("") %>

    <div class="embed_frame"><iframe src="//player.vimeo.com/video/<%= post.embed_link %>?title=0&amp;byline=0&amp;portrait=0&amp;color=fff963" width="100%" max-width="800" height="450" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div>


  <% end %>

<% end %>
</div>

app/views/posts/_form.html.erb
<ul>
  <% @post.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>

<%= form_for(@post) do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :article %>
    <%= f.text_area :article %>
  </p>
  <p>
    <%= f.label :date %>
    <%= f.date_select :date %>
  </p>
  <p>
    <%= f.label :category %>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :embed_link %>
    <%= f.text_field :embed_link %>
  <p>Note: You must use a Youtube, Vimeo URL OR Soundcloud iframe embed code</p>
  </p>
  <p>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
  </p>

  <p><%= f.submit %></p>

<% end %>

app/views/posts/_home.html.erb
<div class="post_info">
<%= link_to( post.title, post_path( post ))%>
<small><span class="separator">by </span> <span class="username_feed"><%= link_to( post.user.username, user_path( post.user )) %></span>  <span class="separator">//</span>  <span class="post_date"> <%= post.date %></span></small>
</div>

<div id="attachment" class="post_content">

<% if post.attachment.present? %>
<div class="containingBlock">
  <div class="embed_frame">
    <%= image_tag post.attachment.url(:medium) %>
</div>
</div>
<% end %><br>
<%= post.article %>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="about_content"><h2>All Posts</h2></div>
<% if session[:current_user] %>
<div id="new_post"><%= link_to('New Post', new_post_path) %></div>
<% end %>

<% @posts.each do |current_post| %>
<div><%= render partial: 'home', locals: { post: current_post } %></div>
<div><%= render partial: 'embed', locals: { post: current_post } %></div>
<hr class="hr_style">
<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<!-- Title Content -->
<div class="about_content">
  <span class="title"><%= @post.title %></span>
  <small><span class="separator">by</span> <span class="username_feed"><%= link_to( @post.user.username, user_path( @post.user )) %></span>  <span class="separator">//</span>  <span class="post_date"><%= @post.date %></span>
</div>

<!-- Photo Attachment -->
<% if @post.attachment.present? %>
  <div class="containingBlock">
    <div class="post_content">
      <div class="embed_frame"><%= image_tag @post.attachment.url(:medium)%></div>
    </div>
  </div>
<% end %>

<!-- Embed Partial -->
<%= render partial: 'embed', locals: { post: @post } %>

<div class="post_content"><%= @post.article %></div>
  <% if @post.category.present? %>
    <div class="post_content">category: <%= @post.category %></div>
  <% end %>

<!-- Post Options / Nav -->
<div class="post_navigation">
  <%= link_to 'Back to Posts', posts_path %>
    <% if session[:current_user] == @post.user.id %>
    <span class="separator">//</span>
      <%= link_to 'Edit Post', edit_post_path%> <span class="separator">//</span>
      <%= link_to 'Delete Post', post_path, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
</div>

<!-- Comments -->
<% unless @post.comments == nil %>
  <h3>Comments</h3>
  <% @post.comments.each do |comment| %>

      <div class="about_content">
        <p>
          <strong>Username:</strong>
          <%= comment.user.username %>
        </p>
        <p>
          <strong>Comment:</strong>
          <%= comment.body %>
        </p>
        <% if session[:current_user] == @post.user_id %>
        <!-- only if post author is logged in, AND he is the comment author, can he delete comments.  need admin?   -->
        <%= link_to 'Delete Comment', [@post, comment], method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>
        <% end %>
      </div>
  <% end %>
<% end %>
<% if session[:current_user] %>
  <h3>Add a comment:</h3>
    <%= render "comments/form" %>
<% end %>