config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end


  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]


  # Sessions
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'



  root to: 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Radiation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header_image">
    <h1 class="banner"><%= link_to('The Radiation', root_path) %></h1>
  </div>
<div class="welcome">
  <nav>
    <span class="main_menu"><%= link_to('Contributors', users_path) %></span>
    <span class="separator">//</span>
    <span class="main_menu"><%= link_to('Our Work', posts_path) %></span>
      <% unless session[:current_user] %>
        <span class="separator">//</span><span id="login_button"><%= link_to('Login', login_path) %></span>
          <span class="separator">//</span><span id="login_button"><%= link_to('Sign Up', new_user_path) %></span>
      <% end %>
  </nav>

  <% if session[:current_user] %>
    <div id="login_box">
      Welcome Back, <%= User.find(session[:current_user]).username %> ! <span class="separator">//</span>
      <span class="logout"><%= link_to('Log Out', logout_path) %></span>
    </div>
  <% end %>

</div>

<%= yield %>

</body>
</html>